# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G

# Fabric Properties
minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
loader_version=0.16.3

minecraft_base_version=1.21

# Mod Properties
mod_version = 1.1.1
maven_group = com.chyzman
archives_base_name = electromechanics

# Dependencies
fabric_version=0.103.0+1.21.1
owo_version=0.12.11+1.21
exp4j_version=0.4.8

accessories_version=1.0.0-beta.31+1.21

lithium=mc1.21.1-0.13.0
modmenu=11.0.2

rei=16.0.754
cloth=15.0.130
arch_api=13.0.6